spring:
    datasource:
       river-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/PilotPersonalCabin
       username: root
       password: 1111
    mustache:
       expose-request-attributes: true
    logging:
       level:
       org.springframework.security: DEBUG
app.menus:
  - title: Home
    name: Home
    path: /
  - title: Login
    name: Login
    path: /login